In [1]:
# Imports
import nltk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import praw

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from reddit_scraper import get_new_data

### Load the Data in

In [2]:
# Retrieve top 1000 posts of all time from r/DungeonsAndDragons and r/Pathfinder_RPG
dnd = get_new_data('DungeonsAndDragons', 1000)
pathfinder = get_new_data('DungeonsAndDragons', 1000)

# Write data to files
dnd.to_csv('../data/dnd.csv')
pathfinder.to_csv('../data/pathfinder.csv')

### Inspect the Data

In [3]:
display(dnd.head())
display(pathfinder.head())

,created_utc,title,self_text,subreddit
0,1.731980e+09,5e.tools,"Hey, I've been using 5e.tools for a little whi...",DungeonsAndDragons
1,1.731975e+09,"Tactical Plastic Report, Episode 3: United Pol...",,DungeonsAndDragons
2,1.731968e+09,DMing at a local cannabis lounge needing campa...,I've been asked to host a DnD night at a local...,DungeonsAndDragons
3,1.731968e+09,I make hand-painted watercolor maps for my D&D...,,DungeonsAndDragons
4,1.731967e+09,Thoughts on how I play Wildfire Druid?,So Wildfire Druid is one of my favorite subcla...,DungeonsAndDragons

,created_utc,title,self_text,subreddit
0,1.731980e+09,5e.tools,"Hey, I've been using 5e.tools for a little whi...",DungeonsAndDragons
1,1.731975e+09,"Tactical Plastic Report, Episode 3: United Pol...",,DungeonsAndDragons
2,1.731968e+09,DMing at a local cannabis lounge needing campa...,I've been asked to host a DnD night at a local...,DungeonsAndDragons
3,1.731968e+09,I make hand-painted watercolor maps for my D&D...,,DungeonsAndDragons
4,1.731967e+09,Thoughts on how I play Wildfire Druid?,So Wildfire Druid is one of my favorite subcla...,DungeonsAndDragons

In [4]:
dnd.shape, pathfinder.shape

((995, 4), (995, 4))

### Check the baseline

### Set up a pipeline to transform the data

### Model Selection Criteria & Explanation

### Fit and Test the Model

### Model Analysis

### Tweak and Repeat